import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/Navbar/Navbar";
import Icons from "./Component/Navbar/shared/Icons/page";
import Footer from "./Component/Navbar/shared/Footer/Footer";
import { Crete_Round } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
const creteRound = Crete_Round({
  subsets: ["latin"],
  weight: ["400"], // Crete Round only has a weight of 400
  variable: "--font-crete-round",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ISTIQBAL",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className={`${creteRound.variable} font-serif`}>
          <Navbar session={session} />
          {children}
        <Icons/>
        <Footer/>
         </div>
       
      </body>
    </html>
  );
}
