import type { Metadata } from "next";
import { Crete_Round } from "next/font/google";
import Footer from "../Component/Navbar/shared/Footer/Footer";
const creteRound = Crete_Round({
  subsets: ["latin"],
  weight: ["400"], // Crete Round only has a weight of 400
  variable: "--font-crete-round",
});


export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`${creteRound.variable} font-serif`}><div className="justify-center text-center items-center m-auto ">
      <div className="bg-slate-100 rounded-xl ml-2">{children}</div>
    </div>
    <Footer/>
    </div>

  );
}
